### PR TITLE
update mapboxgl control system, 0.27.0 fixes

### LINKED ISSUE #94: Use new mapboxgl Control system
https://github.com/mapbox/mapbox-gl-js/pull/3497

The new IControl interface will allow mapbox-gl-directions to remove any dependency on mapboxgl, eliminating a popular class of installation bugs. Once mapboxgl is updated, or before if you're feeling saucy, update to the new interface.

### PR DESCRIPTION
**Pull request by mapsam**
Resolves #94, which opens the door for this plugin to use gl-js `0.27.0`.

### What changed?

* no more reliance on global `mapboxgl` or `window.mapboxgl` within the plugin
* Removed internal usage of `map.addControl` for adding the two geocoders, since we can no longer append controls to custom divs. Since this plugin relied on that, we need to not use the control system internally and just append with `appendChild` to the proper element for the directions UI
* Updated some CSS properties since the directions instructions is now populated directly below the controls, instead of in a custom div
* add circle CI #99 
* remove `require` and just use `import` #96 

TODO

- [x] propogate `accessToken` through to the geocoders. Not sure how to access it at the point of initialization like the directions API does.
- [ ] 👍 👎  on the CSS updates
- [x] update API & readme

cc @tmcw @tristen for the review

### CODE REVIEW

**Comment by mapsam** [comment]
🤔  hmmm tests aren't going to work on CI since we are relying on WebGL to initialize. 

```
[Error: Failed to initialize WebGL]
not ok - this.painter is undefined
```

**Comment by mapsam** [comment]
@tmcw ready for review!

File: src/directions.js [hunk 1]
```diff
@@ -66,12 +50,14 @@ export default class Directions {
...
-    if (controls.inputs) this.container.appendChild(inputEl);
-    if (controls.instructions) this.container.appendChild(directionsEl);
+    if (controls.inputs) el.appendChild(inputEl);
+    el.appendChild(directionsEl);
 
     this.subscribedActions();
     if (this._map.loaded()) this.mapState()
     else this._map.on('load', () => this.mapState());
+
+    return el;
```
Comment (mapsam) [inline src/directions.js]: @tmcw Woops, just added `onRemove`. Good catch!

**Comment by mapsam** [comment]
@tristen I've updated the style _slightly_ and now instructions are located underneath the controls. How do you feel about this update?

screen shot 2016-11-18 at 12 31 34 pm
